// eslint-disable-next-line import/no-anonymous-default-export
export default {
  login: "elvinyeka",
  id: 64169101,
  node_id: "MDQ6VXNlcjY0MTY5MTAx",
  avatar_url: "https://avatars.githubusercontent.com/u/64169101?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/elvinyeka",
  html_url: "https://github.com/elvinyeka",
  followers_url: "https://api.github.com/users/elvinyeka/followers",
  following_url:
    "https://api.github.com/users/elvinyeka/following{/other_user}",
  gists_url: "https://api.github.com/users/elvinyeka/gists{/gist_id}",
  starred_url: "https://api.github.com/users/elvinyeka/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/elvinyeka/subscriptions",
  organizations_url: "https://api.github.com/users/elvinyeka/orgs",
  repos_url: "https://api.github.com/users/elvinyeka/repos",
  events_url: "https://api.github.com/users/elvinyeka/events{/privacy}",
  received_events_url: "https://api.github.com/users/elvinyeka/received_events",
  type: "User",
  site_admin: false,
  name: "Elvin Yekayev",
  company: " BNB Dynamics",
  blog: "",
  location: "Azerbaijan, Baku ",
  email: null,
  hireable: true,
  bio: "React Developer",
  twitter_username: "Elvinyeka",
  public_repos: 38,
  public_gists: 3,
  followers: 71,
  following: 79,
  created_at: "2020-04-22T20:51:34Z",
  updated_at: "2022-09-03T23:53:15Z",
};
